import { getCurrentUser } from '@/lib/auth/get-current-user';
import {
  getByInstitutionBreakdown,
  getPairingCoverage,
  getPerMentorBreakdown,
  getSessionCompletionSummary,
} from '@/lib/services/mentor/session-analytics';
import { resolveAnalyticsScope } from '@/lib/services/mentor/session-analytics-scope';
import {
  byInstitutionToCSV,
  pairingToCSV,
  perMentorToCSV,
  summaryToCSV,
} from '@/lib/utils/analytics-csv';
import { err } from '@/lib/utils/api-response';
import type { AnalyticsFilters } from '@/lib/types/session-analytics';

export const dynamic = 'force-dynamic';

type ExportFormat = 'csv' | 'pdf';
type ExportView = 'summary' | 'per-mentor' | 'pairing' | 'by-institution' | 'full';

/**
 * Build a short human-readable description of the active filters for the PDF
 * cover line. Example: "Dept: <id> · From 2026-04-01 to 2026-04-15"
 */
function buildFiltersDescription(filters: AnalyticsFilters): string {
  const parts: string[] = [];
  if (filters.scopedMentorId) parts.push('Scoped to own mentor');
  if (filters.institutionId) parts.push(`Institution: ${filters.institutionId}`);
  if (filters.departmentId) parts.push(`Department: ${filters.departmentId}`);
  if (filters.dateFrom && filters.dateTo) {
    parts.push(`From ${filters.dateFrom} to ${filters.dateTo}`);
  } else if (filters.dateFrom) {
    parts.push(`From ${filters.dateFrom}`);
  } else if (filters.dateTo) {
    parts.push(`Up to ${filters.dateTo}`);
  }
  return parts.length > 0 ? parts.join(' \u00b7 ') : 'All data (no filters applied)';
}

/**
 * GET /api/mentor/session-analytics/export?format=csv|pdf&view=summary|per-mentor|pairing
 *
 * Streams a downloadable analytics export for the caller's scoped data.
 *
 * Query params (in addition to the standard analytics filters):
 *   - format: 'csv' | 'pdf'        (required)
 *   - view:   'summary' | 'per-mentor' | 'pairing' (required)
 *   - departmentId?: string
 *   - institutionId?: string
 *   - dateFrom?: string (ISO date)
 *   - dateTo?: string (ISO date)
 */
export async function GET(request: Request) {
  try {
    const sp = new URL(request.url).searchParams;

    const format = sp.get('format') as ExportFormat | null;
    const view = sp.get('view') as ExportView | null;

    if (!format || (format !== 'csv' && format !== 'pdf')) {
      return err('Invalid or missing `format` query param (expected csv|pdf)', 400);
    }
    if (
      !view ||
      (view !== 'summary' &&
        view !== 'per-mentor' &&
        view !== 'pairing' &&
        view !== 'by-institution' &&
        view !== 'full')
    ) {
      return err(
        'Invalid or missing `view` query param (expected summary|per-mentor|pairing|by-institution|full)',
        400
      );
    }

    // 'full' is PDF-only (renders all sections); block CSV with this view.
    if (view === 'full' && format === 'csv') {
      return err('`view=full` is only supported for PDF exports', 400);
    }

    const resolution = await resolveAnalyticsScope(sp);
    if (!resolution.ok) return err(resolution.error, resolution.status);
    const filters: AnalyticsFilters = resolution.scope.filters;

    // User info for the PDF header (cover page shows "Generated by <name>").
    const user = await getCurrentUser();

    // by-institution is CSV-only for now; block PDF for this view.
    if (view === 'by-institution') {
      if (resolution.scope.tier !== 'super_admin') {
        return err('Cross-college report is only available to super admins', 403);
      }
      if (format === 'pdf') {
        return err('PDF export is not yet supported for the by-institution view; use CSV', 400);
      }
      const rows = await getByInstitutionBreakdown({
        dateFrom: filters.dateFrom,
        dateTo: filters.dateTo,
      });
      const csvString = byInstitutionToCSV(rows);
      const datestamp = new Date().toISOString().slice(0, 10);
      return new Response(csvString, {
        status: 200,
        headers: {
          'Content-Type': 'text/csv; charset=utf-8',
          'Content-Disposition': `attachment; filename="cross-college-report-${datestamp}.csv"`,
        },
      });
    }

    if (format === 'pdf') {
      const [summary, perMentor, pairings] = await Promise.all([
        getSessionCompletionSummary(filters),
        getPerMentorBreakdown(filters),
        getPairingCoverage(filters),
      ]);
      const { renderAnalyticsPDF } = await import('@/lib/utils/analytics-pdf');
      const pdfView: 'summary' | 'per-mentor' | 'pairing' | 'full' =
        view === 'pairing' || view === 'per-mentor' || view === 'summary' ? view : 'full';
      const buf = await renderAnalyticsPDF({
        view: pdfView,
        summary,
        perMentor,
        pairings,
        generatedAt: new Date().toISOString(),
        generatedBy: user?.full_name || user?.email || 'unknown',
        filtersDescription: buildFiltersDescription(filters),
      });
      const datestampPdf = new Date().toISOString().slice(0, 10);
      return new Response(new Uint8Array(buf), {
        status: 200,
        headers: {
          'Content-Type': 'application/pdf',
          'Content-Disposition': `attachment; filename="session-analytics-${view}-${datestampPdf}.pdf"`,
        },
      });
    }

    // CSV branch
    let csvString: string;
    if (view === 'summary') {
      const summary = await getSessionCompletionSummary(filters);
      csvString = summaryToCSV(summary);
    } else if (view === 'per-mentor') {
      const rows = await getPerMentorBreakdown(filters);
      csvString = perMentorToCSV(rows);
    } else {
      const rows = await getPairingCoverage(filters);
      csvString = pairingToCSV(rows);
    }

    const datestamp = new Date().toISOString().slice(0, 10);
    return new Response(csvString, {
      status: 200,
      headers: {
        'Content-Type': 'text/csv; charset=utf-8',
        'Content-Disposition': `attachment; filename="session-analytics-${view}-${datestamp}.csv"`,
      },
    });
  } catch (error) {
    const message = error instanceof Error ? error.message : 'Internal server error';
    return err(message, 500);
  }
}
